// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/hyperscale/fabric"
	"github.com/hyperscale/fabric/provider/logger"
	"github.com/hyperscale/fabric/provider/mysql"
)

// Injectors from wire.go:

func New() (*fabric.Service, error) {
	configuration, err := fabric.NewConfiguration()
	if err != nil {
		return nil, err
	}
	config, err := logger.ConfigProvider(configuration)
	if err != nil {
		return nil, err
	}
	zerologLogger, err := logger.Factory(config)
	if err != nil {
		return nil, err
	}
	mysqlConfig, err := mysql.ConfigProvider(configuration)
	if err != nil {
		return nil, err
	}
	db, err := mysql.Factory(zerologLogger, mysqlConfig)
	if err != nil {
		return nil, err
	}
	provider := mysql.NewProvider(db)
	options := &Options{
		MySQLProvider: provider,
	}
	service, err := NewApplication(zerologLogger, options)
	if err != nil {
		return nil, err
	}
	return service, nil
}
